Repository hmcts/bulk-scan-payment-processor, pull requests merged in 2019-12, with the labels that each got.

#147 comment about liveness alerts dependency to application name
  src/main/resources/application.yaml
Labels: ns:bulk-scan-payment-processor-pr-147

#148 Suppress jetty dependencies
  config/owasp/suppressions.xml
Labels: ns:bulk-scan-payment-processor-pr-148

#140 Make the application ASE-deployable
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
  web.config
Labels: ns:bulk-scan-payment-processor-pr-140
