Repository hmcts/bulk-scan-payment-processor, pull requests merged in 2020-07, with the labels that each got.

#248 Update test framework
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-248

#249 upgrade service bus version
  build.gradle
  src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/PaymentMessageProcessorTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-249

#255 Bump tomcat 9.0.36 -> 9.0.37
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-255

#262 Use new method signature as jenkins library is updated
  Jenkinsfile_CNP
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-262

#258 Expand payments queue config
  charts/bulk-scan-payment-processor/Chart.yaml
  charts/bulk-scan-payment-processor/values.preview.template.yaml
  charts/bulk-scan-payment-processor/values.yaml
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-258
