Repository hmcts/bulk-scan-payment-processor, pull requests merged in 2020-09, with the labels that each got.

#294 Log ccd errors
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/CcdCallException.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/CcdClient.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/client/CompleteAwaitingDcnProcessingTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-294

#296 Logging PayHub errors
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/payhub/PayHubCallException.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/handler/PaymentMessageHandler.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageHandlerTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-296

#304 Upgrade terraform to 0.13.3
  infrastructure/.terraform-version
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-304

#308 chore: add state to payment-processor
  infrastructure/state.tf
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-308

#310 fix: remove the duplicated RG
  infrastructure/main.tf
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-310
