Repository hmcts/bulk-scan-payment-processor, pull requests merged in 2020-04, with the labels that each got.

#201 Upgrade Gradle version
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:bsp, rel:bulk-scan-payment-processor-pr-201

#203 manual dependabot,Bump guava from 28.2-jre to 29.0-jre #202
  build.gradle
Labels: ns:bsp, rel:bulk-scan-payment-processor-pr-203

#207 use openid token
  build.gradle
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/CcdAuthenticatorFactory.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/CcdAuthenticatorFactoryTest.java
Labels: ns:bsp, rel:bulk-scan-payment-processor-pr-207

#210 bump idam
  build.gradle
Labels: ns:bsp, rel:bulk-scan-payment-processor-pr-210

#211 disable func test
  src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/PaymentForExceptionRecordTest.java
Labels: ns:bsp, rel:bulk-scan-payment-processor-pr-211

#212 Revert "disable func test (#211)" and Revert "use openid token (#207)"
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/PaymentForExceptionRecordTest.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/CcdAuthenticatorFactory.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/CcdAuthenticatorFactoryTest.java
Labels: ns:bsp, rel:bulk-scan-payment-processor-pr-212

#209 Remove ASE as it is deployed to AKS
  infrastructure/demo.tfvars
Labels: ns:bsp, rel:bulk-scan-payment-processor-pr-209
