Repository hmcts/bulk-scan-payment-processor, pull requests merged in 2020-05, with the labels that each got.

#215 Bump log4j 2.12.1 -> 2.13.2
  build.gradle
Labels: ns:bsp, rel:bulk-scan-payment-processor-pr-215

#217 Update java chart to version 2.18.0
  charts/bulk-scan-payment-processor/Chart.yaml
  charts/bulk-scan-payment-processor/requirements.yaml
Labels: ns:bsp, rel:bulk-scan-payment-processor-pr-217

#219 Rename secret sets in Jenkinsfile_CNP
  Jenkinsfile_CNP
Labels: ns:bsp, rel:bulk-scan-payment-processor-pr-219

#221 Removed deprecated config as pipeline will fail otherwise
  Jenkinsfile_CNP
Labels: ns:bsp, rel:bulk-scan-payment-processor-pr-221

#225 Upgrade tomcat embedded jars due to CVE-2020-9484
  build.gradle
Labels: ns:bsp, rel:bulk-scan-payment-processor-pr-225

#223 use new openid token
  build.gradle
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/CcdAuthenticatorFactory.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/CcdAuthenticatorFactoryTest.java
Labels: ns:bsp, rel:bulk-scan-payment-processor-pr-223

#227 remove log
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/CcdAuthenticatorFactory.java
Labels: ns:bsp, rel:bulk-scan-payment-processor-pr-227
