Repository hmcts/bulk-scan-payment-processor, pull requests merged in 2021-03, with the labels that each got.

#386 Suppress vulnerability
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-386

#387 downgrade com.github.ben-manes.versions
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-387

#392 use new env var.
  src/main/resources/application.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-392

#399 dependabot-bumps
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-399

#401 dependabot-org.springframework.boot
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-401

#404 DTSBPS-451: Chart adding processor url
  charts/bulk-scan-payment-processor/Chart.yaml
  charts/bulk-scan-payment-processor/values.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-404

#405 DTSBPS-451: Adding processor client
  src/integrationTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/processor/BulkScanProcessorApiProxyTest.java
  src/integrationTest/resources/application-integration.yaml
  src/integrationTest/resources/testdata.post-processor/payments.json
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/processor/BulkScanProcessorApiProxy.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/processor/CustomFeignErrorDecoder.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/processor/request/PaymentRequest.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/processor/CustomFeignErrorDecoderTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-405

#408 DTSBPS-451: Adding missing processor URL configuration
  src/main/resources/application.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-408

#407 Use config tree
  build.gradle
  charts/bulk-scan-payment-processor/Chart.yaml
  charts/bulk-scan-payment-processor/values.aat.template.yaml
  charts/bulk-scan-payment-processor/values.preview.template.yaml
  charts/bulk-scan-payment-processor/values.yaml
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-407

#409 Dtsbps 451 v3 - Configuration for Async and Retry invocation of bulk scan processor end point
  build.gradle
  src/functionalTest/resources/application.yaml
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/AsyncConfiguration.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/RetryConfig.java
  src/main/resources/application.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-409
