Repository hmcts/bulk-scan-payment-processor, pull requests merged in 2021-08, with the labels that each got.

#491 DTSBPS-687: fortify integration on nightly build
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-491

#492 DTSBPS-695 refactor feign exceptions in tests
  src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/client/CompleteAwaitingDcnProcessingTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/PaymentMessageProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageHandlerTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-492

#505 DTSBPS-722 fix terraform error
  infrastructure/state.tf
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-505
