Repository hmcts/bulk-scan-payment-processor, pull requests merged in 2021-12, with the labels that each got.

#551 DTSBPS-802 upgrade spring boot 2.6.1
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/SwaggerPublisher.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/SwaggerConfiguration.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-551

#553 DTSBPS-802 fix swagger ui
  src/integrationTest/resources/application-integration.yaml
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/SwaggerConfiguration.java
  src/main/resources/application.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-553

#555 remove org.apache.tomcat.embed from dependencymanagement
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-555

#557 Bump log4j version
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-557

#567 Updated fortify release id
  config/fortify-client.properties
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-567
