Repository hmcts/bulk-scan-payment-processor, pull requests merged in 2021-02, with the labels that each got.

#367 suppress-vulnerability
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-367

#379 avoid netty vulnerability
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-379

#380 DTSBPS-369 - update springboot
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-380

#383 bump core-case-data-store-client
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-383

#384 Bump idam-client from v1.5.5 to 2.0.0
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-384
