Repository hmcts/bulk-scan-payment-processor, pull requests merged in 2021-06, with the labels that each got.

#457 remove unnecessary suppressions
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-457

#459 DTSBPS-627 remove unnecessary jars from dependency management
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-459

#465 upgrade gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-465

#466 Update DockerImage to new tagging reference
  Jenkinsfile_CNP
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-466

#468 OWASP-Disable scanning of .NET related binaries
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-468

#470 DTSBPS-644 use new service bus lib
  build.gradle
  charts/bulk-scan-payment-processor/Chart.yaml
  charts/bulk-scan-payment-processor/values.yaml
  src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/FunctionalQueueConfig.java
  src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/helper/PaymentsMessageSender.java
  src/integrationTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/IntegrationContextInitializer.java
  src/integrationTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/task/PaymentMessageProcessTaskTest.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/QueueClientsConfiguration.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/health/QueueHealthIndicator.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageParser.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageProcessor.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/task/PaymentMessageProcessTask.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/data/producer/SamplePaymentMessageData.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/health/QueueHealthIndicatorTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/PaymentMessageProcessorTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageParserTest.java
  src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/task/PaymentMessageProcessTaskTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-470

#472 DTSBPS-644 remove unused env var
  charts/bulk-scan-payment-processor/Chart.yaml
  charts/bulk-scan-payment-processor/values.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-472

#473 DTSBPS-647 change job interval
  charts/bulk-scan-payment-processor/Chart.yaml
  charts/bulk-scan-payment-processor/values.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-473

#475 DTSBPS-650 - upgrade java-chart
  charts/bulk-scan-payment-processor/Chart.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-475
