Repository hmcts/bulk-scan-payment-processor, pull requests merged in 2022-05, with the labels that each got.

#659 Fortify vulnerability
  Dockerfile
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-659

#661 Resolve CVE-2022-24823
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-661

#663 CVE 2016 1000027 vulnerability
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-663

#666 Suppress CVE-2022-29885 (DTSBPS-947)
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-666
