Repository hmcts/bulk-scan-payment-processor, pull requests merged in 2022-09, with the labels that each got.

#740 DTSBPS-1067: Fix CVE-2022-25857
  build.gradle
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-740

#751 Upgrade to Java 17 (DTSBPS-1071)
  Dockerfile
  build.gradle
  charts/bulk-scan-payment-processor/Chart.yaml
  charts/bulk-scan-payment-processor/values.yaml
  config/checkstyle/checkstyle.xml
  lib/AI-Agent.xml
  lib/applicationinsights.json
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/processor/response/PaymentStatusReponse.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageProcessor.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-751

#762 DTSBPS-1084: Added suppression
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-762
