Repository hmcts/bulk-scan-payment-processor, pull requests merged in 2022-11, with the labels that each got.

#804 Suppress Spring-security and tomcat-embed vulnerabilities (DTSBPS-1143)
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-804

#806 DTSBPS-1128: Add payments config for NFD
  charts/bulk-scan-payment-processor/Chart.yaml
  charts/bulk-scan-payment-processor/values.aat.template.yaml
  charts/bulk-scan-payment-processor/values.preview.template.yaml
  charts/bulk-scan-payment-processor/values.yaml
  infrastructure/main.tf
  src/main/resources/application.yaml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-806

#820 DTSBPS-1163: Suppress CVE-2016-1000027
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-820

#826 DTSBPS-1167: Suppress CVE-2022-29885
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-826
