Repository hmcts/bulk-scan-payment-processor, pull requests merged in 2022-04, with the labels that each got.

#630 Suppressed vulnerability
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-630

#633 Suppress vulnerability
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-633

#635 Upgrade Spring Boot version
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-635

#639 Suppress vulnerabilities
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-639
