Repository hmcts/bulk-scan-payment-processor, pull requests merged in 2023-03, with the labels that each got.

#945 Suppress CVE-2023-24998
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-945

#946 DTSBPS-1325: Fix CVE-2023-24998
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-946

#952 DTSBPS-1328 - Bump terraform version and azurerm version
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:bsp, prd:bulk-scan, destroy, rel:bulk-scan-payment-processor-pr-952

#964 Suppress CVE-2022-40152
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-964

#986 local dev changes
  .env
  .gitignore
  charts/bulk-scan-payment-processor/Chart.yaml
  charts/bulk-scan-payment-processor/values.yaml
  config/owasp/suppressions.xml
  docker-compose.yml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-986
