Repository hmcts/bulk-scan-payment-processor, pull requests merged in 2023-01, with the labels that each got.

#864 DTSBPS-1231: Suppressed CVE-2022-40149, CVE-2022-40150, CVE-2022-45693, CVE-2022-4…
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-864

#869 DTSBPS-1235: Suppressed CVE-2021-4277
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-869

#872 DTSBPS-1236: Suppressed dependencies
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-872

#877 DTSBPS-1240: Allow multiple poBoxes
  src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/PaymentForExceptionRecordTest.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/SiteConfiguration.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/SiteConfigurationTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-877

#879 DTSBPS-1240: Revert "DTSBPS-1240: Allow multiple poBoxes (#877)"
  src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/PaymentForExceptionRecordTest.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/SiteConfiguration.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/SiteConfigurationTest.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-879

#899 Upgrade app-insights
  Dockerfile
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-899

#906 DTSBPS-1276: Cleanup suppressions
  config/owasp/suppressions.xml
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-906
