Repository hmcts/bulk-scan-payment-processor, pull requests merged in 2024-10, with the labels that each got.

#1205 updates to get func tests working locally
  src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/JmsPaymentForExceptionRecordTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/PaymentForExceptionRecordTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/helper/CaseSearcher.java
  src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/helper/ExceptionRecordCreator.java
  src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/helper/JmsPaymentsMessageSender.java
  src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/JmsPaymentMessageProcessor.java
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-1205

#1206 FACT-2013 app insights refine logging
  lib/applicationinsights.json
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-1206

#1208 Revert "FACT-2013 app insights refine logging"
  lib/applicationinsights.json
Labels: ns:bsp, prd:bulk-scan, rel:bulk-scan-payment-processor-pr-1208
